// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArPVm3FkBnD_qLUDst_qMGZu73lvYrbkk',
    appId: '1:619424153975:android:43ce9edeecf583d863a172',
    messagingSenderId: '619424153975',
    projectId: 'example-flutter-project',
    storageBucket: 'example-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOBWbG9ay8vUTlk8pwyLVe0lvSUAQokpA',
    appId: '1:619424153975:ios:1c9830d49704cbce63a172',
    messagingSenderId: '619424153975',
    projectId: 'example-flutter-project',
    storageBucket: 'example-flutter-project.appspot.com',
    iosClientId: '619424153975-vtl295tmudjatblel4p80f96u74d4n9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
